### ISSUE TITLE
init error:ytcp:648:tcp(111):Connection refused

### ISSUE THREAD

**Issue by saberioon** [HYPERNETS/hypernets_tools#37]
sequence service is interrupted with this error 

`run_service.sh[2264]: init error:ytcp:648:tcp(111):Connection`

However, I can ping the yoctopuce. 

Besides rebooting the system manually, is there any other solution available to fix this issue?

**Comment by corizzi** [comment]
Hi @saberioon ,

I assume that you are using the firmware firstly provided with the card ? (never updated)
If yes, I guess the best solution is to update. I can provide you information for that.

**Comment by saberioon** [comment]
> Hi @saberioon ,
> 
> I assume that you are using the firmware firstly provided with the card ? (never updated)
> If yes, I guess the best solution is to update. I can provide you information for that.
Hi @corizzi 

Indeed, I haven't updated the firmware. I appreciate any advice or information.

**Comment by corizzi** [comment]
As it is not directly related with this repo. I'll send you by email the dedicated GLPI ticket.

**Comment by javierconcha** [comment]
The system is not working and we are having the same error mentioned in this issue. The rugged-PC stayed ON.

@corizzi , do you suggest updating the  Yoctopuse firmware remotely? Can you point me to which GLPI ticket number describing the update of the firmware?

**Comment by javierconcha** [comment]
We currently have the following firmware:
- VirtualHUB: 40924
- OBSVLFR2-13FA31: Yocto-Pictor-Wifi: 39277

**Comment by corizzi** [comment]
@saberioon, @saberioon : can you confirm that issue was solved with Yocto-Pictor firmware upgrade ?

**Comment by saberioon** [comment]
@corizzi yes, It fixed and our system is online now

**Comment by javierconcha** [comment]
@corizzi Our system is working properly now. Thanks.

**Comment by javierconcha** [comment]
We are still have the following error, even after upgrading the firmware for all devices:

error:ytcp:650:tcp(111):Connection refused

It seems similar to the error reported in this issue.
